export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';
export const CANVAS_CREATED = 'CANVAS_CREATED';
export const CANVAS_UPDATED = 'CANVAS_UPDATED';
export const TOOL_SELECTED = 'TOOL_SELECTED';
export const FURNITURE_ITEM_SELECTED = 'FURNITURE_ITEM_SELECTED';